database:
  host: 2.25.236.90
  port: 1433
  name: Servinet
  username: servinet_api
  password: fdVZPflIR5VOzr

application:
  name: ServiNet
  version: 1.0.0

api-credentials:
  api-peru: #example-token
  whatsapp-api:
    token: #example_token
    instancia: #example_instance

