package org.example.servinet.core.domain.enums;

public enum Permissions {

    BYPASS,

    DASH_VIEW_TOPS,
    DASH_VIEW_GRAPH,
    DASH_VIEW,

    AD_VIEW,
    AD_CREATE_USER,
    AD_VIEW_USERS,
    AD_EDIT_USER,
    AD_DELETE_USER,
    AD_ACTIVITY_VUSERS,
    AD_ACTIVITY_VI,

    APP_CHANGE_NAME,
    APP_CHANGE_LOGO,
    APP_SECURITY_CONFIG,
    APP_GENERAL_CONFIG,
    APP_CONF_SECTOR_ANT,
    APP_CONF_ROL_PERMS,


    ANOUN_CREATE,
    ANOUN_DELETE,

    ANT_MANAGER_ALL,
    ANT_CREATE,
    ANT_DELETE,
    ANT_EDIT,
    ANT_VIEW_INFO,
    ANT_VIEW_ANTENNAS,
    ANT_START_MAINTE,
    ANT_END_MAINT,
    ANT_GO_ACTIVE,
    ANT_GO_DESACTIVE,

    BACKUPS_MANAGER_ALL,

    CLIENTS_MANAGER_ALL,
    CLIENT_DELETE,
    CLIENT_PAY_VIEW,
    CLIENT_INFO,
    CLIENT_SEARCH,

    SELL
}
